### ISSUE TITLE
Controller or Key required - prevent rebuilding on setState

### ISSUE THREAD

**Issue by fly-qp** [Zachariah-Abraham/parallax_rain#1]
Hey first of all great project <3.

Can you please add an controller or a key so the widget won't rebuild on setState() and dont loose state.

**Comment by Zachariah-Abraham** [comment]
Hi @fly-qp 
Thanks :)
Sorry, I wasn't checking my github actively. I'll make the changes you've requested and commit after testing.

**Comment by Zachariah-Abraham** [comment]
@fly-qp 
I've rewritten ParallaxRain's painter to ignore state changes, and I've also included a key param. For some reason, the key param didn't make a difference when used normally (the state changed and a new Painter was initiated for no apparent reason), so I made changes in such a way that state would be ignore with or without the key for the painter (the child widget will still respond to changes in state of course). 

Closing this now, but let me know if you still think it needs modifications.
